services:
  postgres:
    image: postgres:16-alpine
    container_name: easypatch3-db
    environment:
      POSTGRES_DB: easypatch3
      POSTGRES_USER: easypatch3
      POSTGRES_PASSWORD: easypatch3
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - easypatch3-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U easypatch3 -d easypatch3"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./EasyPatchy3.App
      dockerfile: ../Dockerfile
    container_name: easypatch3-app
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=easypatch3;Username=easypatch3;Password=easypatch3"
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8080:8080"
    volumes:
      - ./../Storage:/app/Storage
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - easypatch3-network
    restart: unless-stopped

networks:
  easypatch3-network:
    driver: bridge

volumes:
  postgres-data: